// Barrel export for all constants

export { API_BASE } from './api';

export {
  THEME_STORAGE_KEY,
  APPEARANCE_THEME_STORAGE_KEY,
  INDEXED_DOCUMENTS_STORAGE_KEY,
  PINNED_SESSIONS_STORAGE_KEY,
  RESPONSE_STYLE_STORAGE_KEY,
  VOICE_LOW_RAM_MODE_STORAGE_KEY,
  VOICE_TTS_ENABLED_STORAGE_KEY,
  RAG_ENABLED_STORAGE_KEY,
  RAG_TOP_K_STORAGE_KEY,
  RAG_THRESHOLD_STORAGE_KEY,
} from './storage';

export {
  MAX_PROJECT_FILES,
  MAX_PROJECT_FILE_BYTES,
  MAX_PROJECT_CONTEXT_CHARS,
  IGNORED_PROJECT_DIRECTORIES,
  IGNORED_PROJECT_FILES,
  CODE_PROJECT_EXTENSIONS,
  DEFAULT_WELCOME_MESSAGES,
} from './app';

export {
  MODEL_PROVIDER_TAGS,
  OLLAMA_MODEL_CATALOG,
  EMPTY_CONTEXT_USAGE,
  RESPONSE_STYLE_OPTIONS,
  APPEARANCE_THEME_OPTIONS,
} from './models';
