// Model catalog and provider tag constants
import type { CatalogModel, ResponseStyle } from '../types/index.js';

export const MODEL_PROVIDER_TAGS = [
  'All',
  'Llama',
  'Qwen',
  'DeepSeek',
  'Mistral',
  'Gemma',
  'Phi',
  'Code',
  'Reasoning',
  'Vision',
  'Embedding',
];

export const OLLAMA_MODEL_CATALOG: CatalogModel[] = [
  { name: 'llama3.2:1b', provider: 'Llama', source: 'ollama', tags: ['General'], description: 'Lightweight Llama 3.2 model for very fast local responses.' },
  { name: 'llama3.2:3b', provider: 'Llama', source: 'ollama', tags: ['General'], description: 'Fast general-purpose local model for everyday chat.' },
  { name: 'llama3.1:8b', provider: 'Llama', source: 'ollama', tags: ['General'], description: 'Balanced Llama 3.1 model for local chat and analysis.' },
  { name: 'llama3.1:70b', provider: 'Llama', source: 'ollama', tags: ['General'], description: 'Large Llama 3.1 model for stronger reasoning on high-memory hardware.' },
  { name: 'llama3.1:405b', provider: 'Llama', source: 'ollama', tags: ['General'], description: 'Frontier-scale Llama 3.1 model for very large local or hosted setups.' },
  { name: 'llama3:8b', provider: 'Llama', source: 'ollama', tags: ['General'], description: 'Llama 3 general model with broad local support.' },
  { name: 'llama3:70b', provider: 'Llama', source: 'ollama', tags: ['General'], description: 'Large Llama 3 model for stronger generation quality.' },
  { name: 'codellama:7b', provider: 'Llama', source: 'ollama', tags: ['Code'], description: 'Code-focused Llama model for lightweight programming assistance.' },
  { name: 'codellama:13b', provider: 'Llama', source: 'ollama', tags: ['Code'], description: 'Mid-size Code Llama model for code understanding and generation.' },
  { name: 'codellama:34b', provider: 'Llama', source: 'ollama', tags: ['Code'], description: 'Larger Code Llama model for deeper codebase work.' },
  { name: 'codellama:70b', provider: 'Llama', source: 'ollama', tags: ['Code'], description: 'Large Code Llama model for high-quality coding workflows.' },
  { name: 'llava:7b', provider: 'Llama', source: 'ollama', tags: ['Vision'], description: 'Vision-capable model for image-aware local workflows.' },
  { name: 'llava:13b', provider: 'Llama', source: 'ollama', tags: ['Vision'], description: 'Larger LLaVA model for image-aware local workflows.' },
  { name: 'qwen3:0.6b', provider: 'Qwen', source: 'ollama', tags: ['General'], description: 'Very small Qwen 3 model for quick local responses.' },
  { name: 'qwen3:1.7b', provider: 'Qwen', source: 'ollama', tags: ['General'], description: 'Compact Qwen 3 model for low-resource local use.' },
  { name: 'qwen3:4b', provider: 'Qwen', source: 'ollama', tags: ['General'], description: 'Balanced compact Qwen 3 model.' },
  { name: 'qwen3:8b', provider: 'Qwen', source: 'ollama', tags: ['General'], description: 'General Qwen 3 model with stronger local reasoning.' },
  { name: 'qwen3:14b', provider: 'Qwen', source: 'ollama', tags: ['General'], description: 'Mid-size Qwen 3 model for higher-quality responses.' },
  { name: 'qwen3:30b', provider: 'Qwen', source: 'ollama', tags: ['General'], description: 'Large Qwen 3 model for capable local reasoning.' },
  { name: 'qwen3:32b', provider: 'Qwen', source: 'ollama', tags: ['General'], description: 'Large Qwen 3 model for advanced local workloads.' },
  { name: 'qwen3:235b', provider: 'Qwen', source: 'ollama', tags: ['General'], description: 'Very large Qwen 3 model for high-memory environments.' },
  { name: 'qwen2.5:0.5b', provider: 'Qwen', source: 'ollama', tags: ['General'], description: 'Tiny Qwen 2.5 model for very low-resource devices.' },
  { name: 'qwen2.5:1.5b', provider: 'Qwen', source: 'ollama', tags: ['General'], description: 'Small Qwen 2.5 model for fast local use.' },
  { name: 'qwen2.5:3b', provider: 'Qwen', source: 'ollama', tags: ['General'], description: 'Compact multilingual reasoning model.' },
  { name: 'qwen2.5:7b', provider: 'Qwen', source: 'ollama', tags: ['General'], description: 'Balanced reasoning and writing model.' },
  { name: 'qwen2.5:14b', provider: 'Qwen', source: 'ollama', tags: ['General'], description: 'Mid-size Qwen 2.5 model for stronger multilingual reasoning.' },
  { name: 'qwen2.5:32b', provider: 'Qwen', source: 'ollama', tags: ['General'], description: 'Large Qwen 2.5 model for advanced local workloads.' },
  { name: 'qwen2.5:72b', provider: 'Qwen', source: 'ollama', tags: ['General'], description: 'Large Qwen 2.5 model for high-memory machines.' },
  { name: 'qwen2.5-coder:0.5b', provider: 'Qwen', source: 'ollama', tags: ['Code'], description: 'Tiny Qwen coder model for lightweight coding assistance.' },
  { name: 'qwen2.5-coder:1.5b', provider: 'Qwen', source: 'ollama', tags: ['Code'], description: 'Small Qwen coder model for fast code tasks.' },
  { name: 'qwen2.5-coder:3b', provider: 'Qwen', source: 'ollama', tags: ['Code'], description: 'Compact coding model for local development workflows.' },
  { name: 'qwen2.5-coder:7b', provider: 'Qwen', source: 'ollama', tags: ['Code'], description: 'Coding-focused model for project and patch workflows.' },
  { name: 'qwen2.5-coder:14b', provider: 'Qwen', source: 'ollama', tags: ['Code'], description: 'Mid-size Qwen coder model for stronger code generation.' },
  { name: 'qwen2.5-coder:32b', provider: 'Qwen', source: 'ollama', tags: ['Code'], description: 'Large Qwen coder model for advanced coding tasks.' },
  { name: 'qwen2.5vl:3b', provider: 'Qwen', source: 'ollama', tags: ['Vision'], description: 'Compact Qwen vision-language model.' },
  { name: 'qwen2.5vl:7b', provider: 'Qwen', source: 'ollama', tags: ['Vision'], description: 'Balanced Qwen vision-language model.' },
  { name: 'qwen2.5vl:32b', provider: 'Qwen', source: 'ollama', tags: ['Vision'], description: 'Large Qwen vision-language model.' },
  { name: 'qwen2.5vl:72b', provider: 'Qwen', source: 'ollama', tags: ['Vision'], description: 'Very large Qwen vision-language model.' },
  { name: 'deepseek-r1:1.5b', provider: 'DeepSeek', source: 'ollama', tags: ['Reasoning'], description: 'Small DeepSeek R1 reasoning model.' },
  { name: 'deepseek-r1:7b', provider: 'DeepSeek', source: 'ollama', tags: ['Reasoning'], description: 'Reasoning-oriented model for harder analytical prompts.' },
  { name: 'deepseek-r1:8b', provider: 'DeepSeek', source: 'ollama', tags: ['Reasoning'], description: 'DeepSeek R1 distilled reasoning model.' },
  { name: 'deepseek-r1:14b', provider: 'DeepSeek', source: 'ollama', tags: ['Reasoning'], description: 'Mid-size DeepSeek R1 reasoning model.' },
  { name: 'deepseek-r1:32b', provider: 'DeepSeek', source: 'ollama', tags: ['Reasoning'], description: 'Large DeepSeek R1 reasoning model.' },
  { name: 'deepseek-r1:70b', provider: 'DeepSeek', source: 'ollama', tags: ['Reasoning'], description: 'Large DeepSeek R1 model for high-memory reasoning workloads.' },
  { name: 'deepseek-r1:671b', provider: 'DeepSeek', source: 'ollama', tags: ['Reasoning'], description: 'Very large DeepSeek R1 model for specialized high-memory setups.' },
  { name: 'deepseek-coder:1.3b', provider: 'DeepSeek', source: 'ollama', tags: ['Code'], description: 'Small DeepSeek coder model.' },
  { name: 'deepseek-coder:6.7b', provider: 'DeepSeek', source: 'ollama', tags: ['Code'], description: 'Balanced DeepSeek coder model.' },
  { name: 'deepseek-coder:33b', provider: 'DeepSeek', source: 'ollama', tags: ['Code'], description: 'Large DeepSeek coder model.' },
  { name: 'deepseek-coder-v2:16b', provider: 'DeepSeek', source: 'ollama', tags: ['Code'], description: 'Larger coding model for codebase questions.' },
  { name: 'deepseek-coder-v2:236b', provider: 'DeepSeek', source: 'ollama', tags: ['Code'], description: 'Very large DeepSeek coder model for high-memory setups.' },
  { name: 'deepseek-v2:16b', provider: 'DeepSeek', source: 'ollama', tags: ['General'], description: 'DeepSeek V2 general-purpose model.' },
  { name: 'deepseek-v2:236b', provider: 'DeepSeek', source: 'ollama', tags: ['General'], description: 'Very large DeepSeek V2 model.' },
  { name: 'mistral:7b', provider: 'Mistral', source: 'ollama', tags: ['General'], description: 'Efficient general-purpose model with concise outputs.' },
  { name: 'mistral-nemo:12b', provider: 'Mistral', source: 'ollama', tags: ['General'], description: 'Mistral Nemo model for multilingual local workloads.' },
  { name: 'mixtral:8x7b', provider: 'Mistral', source: 'ollama', tags: ['General'], description: 'Mixture-of-experts Mistral model for stronger generation.' },
  { name: 'mixtral:8x22b', provider: 'Mistral', source: 'ollama', tags: ['General'], description: 'Large Mixtral mixture-of-experts model.' },
  { name: 'codestral:22b', provider: 'Mistral', source: 'ollama', tags: ['Code'], description: 'Mistral coding model for software development tasks.' },
  { name: 'gemma3:1b', provider: 'Gemma', source: 'ollama', tags: ['General'], description: 'Very lightweight Gemma 3 model.' },
  { name: 'gemma3:4b', provider: 'Gemma', source: 'ollama', tags: ['General'], description: 'Compact Gemma 3 model.' },
  { name: 'gemma3:12b', provider: 'Gemma', source: 'ollama', tags: ['General'], description: 'Mid-size Gemma 3 model.' },
  { name: 'gemma3:27b', provider: 'Gemma', source: 'ollama', tags: ['General'], description: 'Large Gemma 3 model.' },
  { name: 'gemma2:2b', provider: 'Gemma', source: 'ollama', tags: ['General'], description: 'Very lightweight model for quick local responses.' },
  { name: 'gemma2:9b', provider: 'Gemma', source: 'ollama', tags: ['General'], description: 'Higher-quality Gemma model for writing and reasoning.' },
  { name: 'gemma2:27b', provider: 'Gemma', source: 'ollama', tags: ['General'], description: 'Large Gemma 2 model for higher-quality responses.' },
  { name: 'codegemma:2b', provider: 'Gemma', source: 'ollama', tags: ['Code'], description: 'Small Gemma coding model.' },
  { name: 'codegemma:7b', provider: 'Gemma', source: 'ollama', tags: ['Code'], description: 'Gemma coding model for local development tasks.' },
  { name: 'phi3:mini', provider: 'Phi', source: 'ollama', tags: ['General'], description: 'Small model for low-resource devices.' },
  { name: 'phi3:medium', provider: 'Phi', source: 'ollama', tags: ['General'], description: 'Mid-size Phi 3 model.' },
  { name: 'phi4', provider: 'Phi', source: 'ollama', tags: ['General'], description: 'Phi 4 model for capable local reasoning and writing.' },
  { name: 'phi4-mini', provider: 'Phi', source: 'ollama', tags: ['General'], description: 'Compact Phi 4 model for efficient local use.' },
  { name: 'nomic-embed-text', provider: 'Embedding', source: 'ollama', tags: ['Embedding'], description: 'Text embedding model for retrieval and semantic search workflows.' },
  { name: 'mxbai-embed-large', provider: 'Embedding', source: 'ollama', tags: ['Embedding'], description: 'Large embedding model for semantic retrieval.' },
  { name: 'mistral-7b-instruct-v0.3-gguf', provider: 'Mistral', source: 'huggingface', tags: ['General'], description: 'Mistral 7B Instruct v0.3 GGUF from lmstudio-community.' },
  { name: 'mistral-7b-v0.3-gguf', provider: 'Mistral', source: 'huggingface', tags: ['General'], description: 'Mistral 7B v0.3 base GGUF from lmstudio-community.' },
  { name: 'mixtral-8x7b-instruct-v0.1-gguf', provider: 'Mistral', source: 'huggingface', tags: ['General'], description: 'Mixtral 8x7B Instruct v0.1 GGUF from lmstudio-community.' },
  { name: 'llama-3.2-1b-instruct-gguf', provider: 'Llama', source: 'huggingface', tags: ['General'], description: 'Llama 3.2 1B Instruct GGUF from lmstudio-community.' },
  { name: 'llama-3.2-3b-instruct-gguf', provider: 'Llama', source: 'huggingface', tags: ['General'], description: 'Llama 3.2 3B Instruct GGUF from lmstudio-community.' },
  { name: 'llama-3.1-8b-instruct-gguf', provider: 'Llama', source: 'huggingface', tags: ['General'], description: 'Llama 3.1 8B Instruct GGUF from lmstudio-community.' },
  { name: 'llama-3.1-70b-instruct-gguf', provider: 'Llama', source: 'huggingface', tags: ['General'], description: 'Llama 3.1 70B Instruct GGUF from lmstudio-community.' },
  { name: 'llama-3.1-405b-instruct-gguf', provider: 'Llama', source: 'huggingface', tags: ['General'], description: 'Llama 3.1 405B Instruct GGUF from lmstudio-community.' },
  { name: 'codegemma-7b-gguf', provider: 'Gemma', source: 'huggingface', tags: ['Code'], description: 'CodeGemma 7B GGUF from lmstudio-community.' },
  { name: 'gemma-2-9b-it-gguf', provider: 'Gemma', source: 'huggingface', tags: ['General'], description: 'Gemma 2 9B Instruct GGUF from lmstudio-community.' },
  { name: 'gemma-2-27b-it-gguf', provider: 'Gemma', source: 'huggingface', tags: ['General'], description: 'Gemma 2 27B Instruct GGUF from lmstudio-community.' },
  { name: 'qwen2.5-7b-instruct-gguf', provider: 'Qwen', source: 'huggingface', tags: ['General'], description: 'Qwen 2.5 7B Instruct GGUF from lmstudio-community.' },
  { name: 'qwen2.5-14b-instruct-gguf', provider: 'Qwen', source: 'huggingface', tags: ['General'], description: 'Qwen 2.5 14B Instruct GGUF from lmstudio-community.' },
  { name: 'qwen2.5-32b-instruct-gguf', provider: 'Qwen', source: 'huggingface', tags: ['General'], description: 'Qwen 2.5 32B Instruct GGUF from lmstudio-community.' },
  { name: 'qwen2.5-72b-instruct-gguf', provider: 'Qwen', source: 'huggingface', tags: ['General'], description: 'Qwen 2.5 72B Instruct GGUF from lmstudio-community.' },
  { name: 'qwen2.5-coder-7b-instruct-gguf', provider: 'Qwen', source: 'huggingface', tags: ['Code'], description: 'Qwen 2.5 Coder 7B GGUF from lmstudio-community.' },
  { name: 'qwen2.5-coder-14b-instruct-gguf', provider: 'Qwen', source: 'huggingface', tags: ['Code'], description: 'Qwen 2.5 Coder 14B GGUF from lmstudio-community.' },
  { name: 'deepseek-r1-distill-qwen-7b-gguf', provider: 'DeepSeek', source: 'huggingface', tags: ['Reasoning'], description: 'DeepSeek R1 Distill Qwen 7B GGUF from lmstudio-community.' },
  { name: 'deepseek-r1-distill-qwen-14b-gguf', provider: 'DeepSeek', source: 'huggingface', tags: ['Reasoning'], description: 'DeepSeek R1 Distill Qwen 14B GGUF from lmstudio-community.' },
  { name: 'deepseek-r1-distill-qwen-32b-gguf', provider: 'DeepSeek', source: 'huggingface', tags: ['Reasoning'], description: 'DeepSeek R1 Distill Qwen 32B GGUF from lmstudio-community.' },
  { name: 'phi-4-gguf', provider: 'Phi', source: 'huggingface', tags: ['General'], description: 'Phi 4 GGUF from lmstudio-community.' },
  { name: 'phi-3-mini-4k-instruct-gguf', provider: 'Phi', source: 'huggingface', tags: ['General'], description: 'Phi 3 Mini 4K Instruct GGUF from lmstudio-community.' },
];

export const EMPTY_CONTEXT_USAGE = {
  provider: '',
  model: '',
  used_tokens: 0,
  context_window: 0,
  usage_source: 'not-loaded',
};

export const RESPONSE_STYLE_OPTIONS: Array<{ value: ResponseStyle; label: string; description: string }> = [
  { value: 'default', label: 'Default', description: 'Balanced, direct, and close to the original AEGIS assistant behavior.' },
  { value: 'friendly', label: 'Friendly', description: 'Warmer and more conversational while staying concise.' },
  { value: 'concise', label: 'Concise', description: 'Shorter answers that prioritize the direct result.' },
  { value: 'elaborate', label: 'Elaborate', description: 'More detailed explanations with fuller context and reasoning.' },
  { value: 'technical', label: 'Technical', description: 'Precise engineering-oriented responses with implementation detail.' },
];

export const APPEARANCE_THEME_OPTIONS: Array<{
  value: string; label: string; description: string; preview: string;
}> = [
  { value: 'default', label: 'Default', description: 'The current AEGIS emerald look with the clean baseline palette.', preview: 'linear-gradient(135deg, #10b981 0%, #047857 100%)' },
  { value: 'terminal', label: 'Terminal', description: 'Neon green accents with a sharper operator-console feel.', preview: 'linear-gradient(135deg, #84cc16 0%, #14532d 100%)' },
  { value: 'ocean', label: 'Ocean', description: 'Cool cyan and deep blue accents for a crisp analytical feel.', preview: 'linear-gradient(135deg, #38bdf8 0%, #1d4ed8 100%)' },
  { value: 'ember', label: 'Ember', description: 'Copper-orange highlights with a more energetic operations tone.', preview: 'linear-gradient(135deg, #fb923c 0%, #b45309 100%)' },
  { value: 'rose', label: 'Rose', description: 'Soft magenta accents for a warmer, more editorial presentation.', preview: 'linear-gradient(135deg, #f472b6 0%, #be185d 100%)' },
  { value: 'slate', label: 'Slate', description: 'Subdued steel-blue accents for a quieter, more minimal workspace.', preview: 'linear-gradient(135deg, #94a3b8 0%, #334155 100%)' },
];
