; AEGIS Windows Installer — NSIS script
; Bundles pre-compiled engine.exe, cli.exe, and frontend dist/

!define PRODUCT_NAME "AEGIS"
!define PRODUCT_VERSION "0.1.0"
!define PRODUCT_PUBLISHER "Nous Research"
!define PRODUCT_WEB_SITE "https://github.com/NousResearch/AEGIS"

Unicode true
RequestExecutionLevel admin

; --- Interface Settings ---
!include "MUI2.nsh"
!include "FileFunc.nsh"
!include "WinCore.nsh"

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "AEGIS-Windows-x64.exe"
InstallDir "$LOCALAPPDATA\AEGIS"

; Check for existing install; read previous InstallDir from registry
InstallDirRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AEGIS" "InstallLocation"

; --- Pages ---
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "..\LICENSE"
!insertmacro MUI_PAGE_DIRECTORY

; Components page
!insertmacro MUI_PAGE_COMPONENTS

; Instfiles page
!insertmacro MUI_PAGE_INSTFILES

; Finish page with run checkbox
!define MUI_FINISHPAGE_RUN "$INSTDIR\bin\aegis.exe"
!define MUI_FINISHPAGE_RUN_TEXT "Launch AEGIS after setup"
!define MUI_FINISHPAGE_LINK "View documentation"
!define MUI_FINISHPAGE_LINK_LOCATION "https://github.com/NousResearch/AEGIS"
!define MUI_FINISHPAGE_NOREBOOT_SUPPORT
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

; --- Languages ---
!insertmacro MUI_LANGUAGE "English"

; --- Install Sections ---

Section "AEGIS Core (required)" SecCore
    SectionIn RO
    SetOutPath "$INSTDIR"

    ; Create directory structure
    CreateDirectory "$INSTDIR\bin"
    CreateDirectory "$INSTDIR\frontend\dist"
    CreateDirectory "$INSTDIR\.aegis\config"
    CreateDirectory "$INSTDIR\.aegis\logs"
    CreateDirectory "$INSTDIR\.aegis\sessions"

    ; Copy binaries
    File /oname=bin\aegis-engine.exe "..\build\release\aegis-engine.exe"
    File /oname=bin\aegis.exe "..\build\release\aegis.exe"

    ; Copy frontend dist (fixed syntax)
    SetOutPath "$INSTDIR\frontend\dist"
    File /r /x *.map /x *.ts /x node_modules "..\frontend\dist\*.*"
    SetOutPath "$INSTDIR"

    ; Write a default aegis.toml (minimal, since `aegis install --yes` will overwrite it)
    FileOpen $0 "$INSTDIR\.aegis\config\aegis.toml" w
    FileWrite $0 "# AEGIS configuration$\r$\n"
    FileWrite $0 "# Generated by installer$\r$\n"
    FileWrite $0 "$\r$\n"
    FileWrite $0 "[server]$\r$\n"
    FileWrite $0 'host = "127.0.0.1"$\r$\n'
    FileWrite $0 'port = "8080"$\r$\n'
    FileWrite $0 "$\r$\n"
    FileWrite $0 "[inference]$\r$\n"
    FileWrite $0 'provider = "ollama"$\r$\n'
    FileWrite $0 'base_url = "http://127.0.0.1:11434"$\r$\n'
    FileWrite $0 "$\r$\n"
    FileWrite $0 "[rag]$\r$\n"
    FileWrite $0 'base_url = "http://127.0.0.1:8000"$\r$\n'
    FileWrite $0 'venv_path = "$INSTDIR\rag-env"$\r$\n'
    FileClose $0

    ; Write version info file
    FileOpen $0 "$INSTDIR\AEGIS_VERSION" w
    FileWrite $0 "${PRODUCT_VERSION}"
    FileClose $0

    ; Write uninstaller
    WriteUninstaller "$INSTDIR\uninstall.exe"

    ; Create Start Menu shortcuts
    CreateDirectory "$SMPROGRAMS\AEGIS"
    CreateShortCut "$SMPROGRAMS\AEGIS\AEGIS Shell.lnk" "$INSTDIR\bin\aegis.exe" "" "$INSTDIR\bin\aegis.exe" 0
    CreateShortCut "$SMPROGRAMS\AEGIS\AEGIS Engine.lnk" "$INSTDIR\bin\aegis-engine.exe" "" "$INSTDIR\bin\aegis-engine.exe" 0
    CreateShortCut "$SMPROGRAMS\AEGIS\Uninstall AEGIS.lnk" "$INSTDIR\uninstall.exe" "" "$INSTDIR\uninstall.exe" 0
    CreateShortCut "$SMPROGRAMS\AEGIS\Documentation.lnk" "https://github.com/NousResearch/AEGIS"

    ; Registry for uninstall
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AEGIS" \
        "DisplayName" "AEGIS - Your Local AI Assistant"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AEGIS" \
        "DisplayVersion" "${PRODUCT_VERSION}"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AEGIS" \
        "Publisher" "${PRODUCT_PUBLISHER}"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AEGIS" \
        "InstallLocation" "$INSTDIR"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AEGIS" \
        "UninstallString" "$INSTDIR\uninstall.exe"
    WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AEGIS" \
        "NoModify" 1
    WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AEGIS" \
        "NoRepair" 1
SectionEnd

Section "Add AEGIS to PATH" SecPath
    ; Use direct registry manipulation instead of EnVar plugin
    ; Read current user PATH
    ReadRegStr $0 HKCU "Environment" "PATH"
    ${If} $0 != ""
        ; Check if already in PATH
        ${If} $0 != ""
            Push "$0"
            Push "$INSTDIR\bin"
            Call StrStr
            Pop $1
            ${If} $1 == ""
                ; Append to PATH
                StrCpy $0 "$0;$INSTDIR\bin"
                WriteRegExpandStr HKCU "Environment" "PATH" "$0"
                DetailPrint "Added $INSTDIR\bin to PATH"
            ${Else}
                DetailPrint "$INSTDIR\bin already in PATH"
            ${EndIf}
        ${EndIf}
    ${Else}
        WriteRegExpandStr HKCU "Environment" "PATH" "$INSTDIR\bin"
        DetailPrint "Set PATH to $INSTDIR\bin"
    ${EndIf}
    ; Notify system of environment change
    SendMessage ${HWND_BROADCAST} ${WM_WININICHANGE} 0 "STR:Environment" /TIMEOUT=5000
SectionEnd

Section "Desktop shortcut" SecDesktop
    CreateShortCut "$DESKTOP\AEGIS.lnk" "$INSTDIR\bin\aegis.exe" "" "$INSTDIR\bin\aegis.exe" 0
SectionEnd

; --- Helper function for string search ---
Function StrStr
    Exch $R1 ; string to search for
    Exch 1
    Exch $R0 ; string to search in
    Push $R2
    Push $R3
    Push $R4
    Push $R5
    StrLen $R2 $R0
    StrLen $R3 $R1
    IntOp $R4 0
    ${DoWhile} $R4 < $R2
        StrCpy $R5 $R0 $R3 $R4
        ${If} $R5 == $R1
            StrCpy $R0 $R4
            ${ExitDo}
        ${EndIf}
        IntOp $R4 $R4 + 1
    ${Loop}
    ${If} $R4 >= $R2
        StrCpy $R0 ""
    ${EndIf}
    Pop $R5
    Pop $R4
    Pop $R3
    Pop $R2
    Exch $R0
    Exch
    Pop $R1
FunctionEnd

; --- Descriptions ---
LangString DESC_SecCore ${LANG_ENGLISH} "Core AEGIS files: engine, CLI, and web UI."
LangString DESC_SecPath ${LANG_ENGLISH} "Add the AEGIS bin folder to the user PATH so you can run `aegis` from any terminal."
LangString DESC_SecDesktop ${LANG_ENGLISH} "Create a desktop shortcut for the AEGIS CLI."

!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
    !insertmacro MUI_DESCRIPTION_TEXT ${SecCore} $(DESC_SecCore)
    !insertmacro MUI_DESCRIPTION_TEXT ${SecPath} $(DESC_SecPath)
    !insertmacro MUI_DESCRIPTION_TEXT ${SecDesktop} $(DESC_SecDesktop)
!insertmacro MUI_FUNCTION_DESCRIPTION_END

; --- Uninstaller ---
Section "Uninstall"
    ; Remove shortcuts
    RMDir /r "$SMPROGRAMS\AEGIS"
    Delete "$DESKTOP\AEGIS.lnk"

    ; Remove PATH entry using direct registry manipulation
    ReadRegStr $0 HKCU "Environment" "PATH"
    ${If} $0 != ""
        Push "$0"
        Push "$INSTDIR\bin"
        Call StrStr
        Pop $1
        ${If} $1 != ""
            ; Remove the entry from PATH
            StrCpy $0 "$0"
            ; Simple: replace ";$INSTDIR\bin" with ""
            Push "$0"
            Push ";$INSTDIR\bin"
            Call StrStrip
            Pop $0
            ; Also try without leading semicolon
            Push "$0"
            Push "$INSTDIR\bin;"
            Call StrStrip
            Pop $0
            ; Also try exact match
            Push "$0"
            Push "$INSTDIR\bin"
            Call StrStrip
            Pop $0
            WriteRegExpandStr HKCU "Environment" "PATH" "$0"
            DetailPrint "Removed $INSTDIR\bin from PATH"
        ${EndIf}
    ${EndIf}

    ; Remove install directory
    RMDir /r "$INSTDIR\bin"
    RMDir /r "$INSTDIR\frontend"
    RMDir /r "$INSTDIR\.aegis"
    Delete "$INSTDIR\uninstall.exe"
    Delete "$INSTDIR\AEGIS_VERSION"
    RMDir "$INSTDIR"

    ; Remove registry key
    DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AEGIS"

    ; Notify system of environment change
    SendMessage ${HWND_BROADCAST} ${WM_WININICHANGE} 0 "STR:Environment" /TIMEOUT=5000
SectionEnd

; --- Helper function to strip a substring ---
Function StrStrip
    Exch $R1 ; substring to remove
    Exch 1
    Exch $R0 ; string to process
    Push $R2
    Push $R3
    Push $R4
    Push $R5
    StrLen $R2 $R1
    ${If} $R2 = 0
        Pop $R5
        Pop $R4
        Pop $R3
        Pop $R2
        Exch $R0
        Exch
        Pop $R1
        Return
    ${EndIf}
    StrCpy $R3 ""
    ${Do}
        Push "$R0"
        Push "$R1"
        Call StrStr
        Pop $R4
        ${If} $R4 == ""
            StrCpy $R3 "$R3$R0"
            ${ExitDo}
        ${EndIf}
        StrCpy $R5 $R0 $R4
        StrCpy $R3 "$R3$R5"
        IntOp $R4 $R4 + $R2
        StrCpy $R0 $R0 "" $R4
    ${Loop}
    Pop $R5
    Pop $R4
    Pop $R3
    Pop $R2
    Exch $R3
    Exch
    Pop $R1
FunctionEnd
