; AEGIS Windows Installer — NSIS script
; Bundles pre-compiled engine.exe, cli.exe, and frontend dist/

!define PRODUCT_NAME "AEGIS"
!define PRODUCT_VERSION "0.1.0"
!define PRODUCT_PUBLISHER "Nous Research"

Unicode true
RequestExecutionLevel admin

!include "MUI2.nsh"
!include "FileFunc.nsh"

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "AEGIS-Windows-x64.exe"
InstallDir "$LOCALAPPDATA\AEGIS"
InstallDirRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AEGIS" "InstallLocation"

; --- Pages ---
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES

; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\bin\aegis.exe"
!define MUI_FINISHPAGE_RUN_TEXT "Launch AEGIS after setup"
!define MUI_FINISHPAGE_LINK "View documentation"
!define MUI_FINISHPAGE_LINK_LOCATION "https://github.com/NousResearch/AEGIS"
!define MUI_FINISHPAGE_NOREBOOT_SUPPORT
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "English"

; --- Install ---
Section "Install"
    SectionIn RO
    SetOutPath "$INSTDIR"

    CreateDirectory "$INSTDIR\bin"
    CreateDirectory "$INSTDIR\.aegis\config"
    CreateDirectory "$INSTDIR\.aegis\logs"
    CreateDirectory "$INSTDIR\.aegis\sessions"

    File /oname=bin\aegis-engine.exe "..\build\release\aegis-engine.exe"
    File /oname=bin\aegis.exe "..\build\release\aegis.exe"

    SetOutPath "$INSTDIR\frontend\dist"
    File /r /x *.map /x *.ts /x node_modules "..\frontend\dist\*.*"
    SetOutPath "$INSTDIR"

    ; Write aegis.toml
    FileOpen $0 "$INSTDIR\.aegis\config\aegis.toml" w
    FileWrite $0 "# AEGIS configuration$\r$\n"
    FileWrite $0 "# Generated by installer$\r$\n"
    FileWrite $0 "$\r$\n"
    FileWrite $0 "[server]$\r$\n"
    FileWrite $0 'host = "127.0.0.1"$\r$\n'
    FileWrite $0 'port = "8080"$\r$\n'
    FileWrite $0 "$\r$\n"
    FileWrite $0 "[inference]$\r$\n"
    FileWrite $0 'provider = "ollama"$\r$\n'
    FileWrite $0 'base_url = "http://127.0.0.1:11434"$\r$\n'
    FileWrite $0 "$\r$\n"
    FileWrite $0 "[rag]$\r$\n"
    FileWrite $0 'base_url = "http://127.0.0.1:8000"$\r$\n'
    FileClose $0

    FileOpen $0 "$INSTDIR\AEGIS_VERSION" w
    FileWrite $0 "${PRODUCT_VERSION}"
    FileClose $0

    WriteUninstaller "$INSTDIR\uninstall.exe"

    ; Start Menu
    CreateDirectory "$SMPROGRAMS\AEGIS"
    CreateShortCut "$SMPROGRAMS\AEGIS\AEGIS Shell.lnk" "$INSTDIR\bin\aegis.exe"
    CreateShortCut "$SMPROGRAMS\AEGIS\AEGIS Engine.lnk" "$INSTDIR\bin\aegis-engine.exe"
    CreateShortCut "$SMPROGRAMS\AEGIS\Uninstall AEGIS.lnk" "$INSTDIR\uninstall.exe"

    ; Desktop shortcut
    CreateShortCut "$DESKTOP\AEGIS.lnk" "$INSTDIR\bin\aegis.exe"

    ; Add to PATH — only append if the user PATH already exists.
    ; If HKCU PATH is empty/non-existent, skip modification entirely.
    ; Creating a new HKCU PATH would override the implicit merge with
    ; the system (HKLM) PATH and could wipe HKLM-only entries from the
    ; effective user PATH in some shells.
    DetailPrint "Adding AEGIS to user PATH..."
    ReadRegStr $1 HKCU "Environment" "PATH"
    ${If} $1 != ""
        ${If} $1 != "$INSTDIR\bin"
        ${AndIf} $1 != "$INSTDIR\bin;"
            StrCpy $1 "$1;$INSTDIR\bin"
        ${EndIf}
        WriteRegStr HKCU "Environment" "PATH" $1
        DetailPrint "AEGIS added to user PATH."
    ${Else}
        DetailPrint "No existing user PATH found — skipping PATH modification."
        DetailPrint "Add $INSTDIR\bin to your PATH manually, or run AEGIS from the Start Menu shortcut."
    ${EndIf}
    SendMessage ${HWND_BROADCAST} ${WM_WININICHANGE} 0 "STR:Environment" /TIMEOUT=5000

    ; Registry for uninstall
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AEGIS" \
        "DisplayName" "AEGIS - Your Local AI Assistant"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AEGIS" \
        "DisplayVersion" "${PRODUCT_VERSION}"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AEGIS" \
        "Publisher" "${PRODUCT_PUBLISHER}"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AEGIS" \
        "InstallLocation" "$INSTDIR"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AEGIS" \
        "UninstallString" "$INSTDIR\uninstall.exe"
    WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AEGIS" \
        "NoModify" 1
    WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AEGIS" \
        "NoRepair" 1
SectionEnd

; --- Uninstall ---
Section "Uninstall"
    RMDir /r "$SMPROGRAMS\AEGIS"
    Delete "$DESKTOP\AEGIS.lnk"
    RMDir /r "$INSTDIR\bin"
    RMDir /r "$INSTDIR\frontend"
    RMDir /r "$INSTDIR\.aegis"
    Delete "$INSTDIR\uninstall.exe"
    Delete "$INSTDIR\AEGIS_VERSION"
    RMDir "$INSTDIR"
    DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AEGIS"
SectionEnd
